"""Add pool metrics and monitoring tables

Revision ID: 30ff38b3b56d
Revises: 001
Create Date: 2025-08-14 09:53:14.524611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ff38b3b56d'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_metrics',
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('total_volume_usdc', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('deposit_volume_usdc', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('withdrawal_volume_usdc', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('positions_opened', sa.Integer(), nullable=False),
    sa.Column('positions_closed', sa.Integer(), nullable=False),
    sa.Column('active_positions', sa.Integer(), nullable=False),
    sa.Column('active_users', sa.Integer(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('total_tvl_usdc', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_fees_earned_usdc', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_rewards_earned_usdc', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('protocol_fees_collected_usdc', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_pnl_usdc', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('average_apr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('best_performing_pool', sa.String(), nullable=True),
    sa.Column('worst_performing_pool', sa.String(), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('failed_transactions', sa.Integer(), nullable=False),
    sa.Column('average_gas_used', sa.Numeric(precision=20, scale=9), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('metric_date', 'metric_type', name=op.f('pk_daily_metrics')),
    sa.UniqueConstraint('metric_date', 'metric_type', name='uq_daily_metrics_date_type')
    )
    op.create_index('idx_daily_metrics_date', 'daily_metrics', ['metric_date'], unique=False)
    op.create_index('idx_daily_metrics_tvl', 'daily_metrics', ['total_tvl_usdc'], unique=False)
    op.create_index('idx_daily_metrics_type', 'daily_metrics', ['metric_type'], unique=False)
    op.create_index('idx_daily_metrics_volume', 'daily_metrics', ['total_volume_usdc'], unique=False)
    op.create_table('executor_stats',
    sa.Column('executor_id', sa.String(), nullable=False),
    sa.Column('executor_name', sa.String(), nullable=True),
    sa.Column('executor_type', sa.String(), nullable=True),
    sa.Column('active_wallets', sa.Integer(), nullable=False),
    sa.Column('total_positions', sa.Integer(), nullable=False),
    sa.Column('active_positions', sa.Integer(), nullable=False),
    sa.Column('total_volume_executed', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_fees_collected', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_healthy', sa.Boolean(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('last_error_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('executor_id', name=op.f('pk_executor_stats'))
    )
    op.create_index('idx_executor_stats_active', 'executor_stats', ['active_positions'], unique=False)
    op.create_index('idx_executor_stats_healthy', 'executor_stats', ['is_healthy'], unique=False)
    op.create_index('idx_executor_stats_heartbeat', 'executor_stats', ['last_heartbeat'], unique=False)
    op.create_index('idx_executor_stats_type', 'executor_stats', ['executor_type'], unique=False)
    op.create_index(op.f('ix_executor_stats_executor_id'), 'executor_stats', ['executor_id'], unique=False)
    op.create_table('pool_metrics',
    sa.Column('pool_address', sa.String(), nullable=False),
    sa.Column('tvl_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('volume_24h', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('apr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tick_spacing', sa.Integer(), nullable=True),
    sa.Column('fee_tier', sa.Integer(), nullable=True),
    sa.Column('is_stable', sa.Boolean(), nullable=False),
    sa.Column('current_tick', sa.Integer(), nullable=True),
    sa.Column('sqrt_price_x96', sa.String(), nullable=True),
    sa.Column('gauge_address', sa.String(), nullable=True),
    sa.Column('token0_address', sa.String(), nullable=True),
    sa.Column('token1_address', sa.String(), nullable=True),
    sa.Column('token0_symbol', sa.String(), nullable=True),
    sa.Column('token1_symbol', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('pool_address', name=op.f('pk_pool_metrics'))
    )
    op.create_index('idx_pool_metrics_apr', 'pool_metrics', ['apr'], unique=False)
    op.create_index('idx_pool_metrics_gauge', 'pool_metrics', ['gauge_address'], unique=False)
    op.create_index('idx_pool_metrics_is_stable', 'pool_metrics', ['is_stable'], unique=False)
    op.create_index('idx_pool_metrics_tvl', 'pool_metrics', ['tvl_usd'], unique=False)
    op.create_index('idx_pool_metrics_updated_at', 'pool_metrics', ['updated_at'], unique=False)
    op.create_index('idx_pool_metrics_volume', 'pool_metrics', ['volume_24h'], unique=False)
    op.create_index(op.f('ix_pool_metrics_pool_address'), 'pool_metrics', ['pool_address'], unique=False)
    op.create_table('strategy_decisions',
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('decision_type', sa.String(), nullable=False),
    sa.Column('pool_address', sa.String(), nullable=False),
    sa.Column('action_recommended', sa.String(), nullable=False),
    sa.Column('recommended_amount_usdc', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('recommended_tick_lower', sa.Integer(), nullable=True),
    sa.Column('recommended_tick_upper', sa.Integer(), nullable=True),
    sa.Column('pool_tvl', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pool_volume_24h', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pool_apr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_tick', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('expected_return', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('decision_metadata', sa.JSON(), nullable=True),
    sa.Column('was_executed', sa.Boolean(), nullable=False),
    sa.Column('execution_tx_hash', sa.String(), nullable=True),
    sa.Column('execution_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_result', sa.String(), nullable=True),
    sa.Column('actual_pnl', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('actual_apr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('decision_id', name=op.f('pk_strategy_decisions'))
    )
    op.create_index('idx_strategy_decision_action', 'strategy_decisions', ['action_recommended'], unique=False)
    op.create_index('idx_strategy_decision_created', 'strategy_decisions', ['created_at'], unique=False)
    op.create_index('idx_strategy_decision_executed', 'strategy_decisions', ['was_executed'], unique=False)
    op.create_index('idx_strategy_decision_pool', 'strategy_decisions', ['pool_address'], unique=False)
    op.create_index('idx_strategy_decision_type', 'strategy_decisions', ['decision_type'], unique=False)
    op.create_index('idx_strategy_decision_user', 'strategy_decisions', ['user_id'], unique=False)
    op.create_index(op.f('ix_strategy_decisions_pool_address'), 'strategy_decisions', ['pool_address'], unique=False)
    op.create_index(op.f('ix_strategy_decisions_request_id'), 'strategy_decisions', ['request_id'], unique=False)
    op.create_index(op.f('ix_strategy_decisions_user_id'), 'strategy_decisions', ['user_id'], unique=False)
    op.create_index(op.f('ix_positions_pool_address'), 'positions', ['pool_address'], unique=False)
    op.create_index(op.f('ix_positions_user_id'), 'positions', ['user_id'], unique=False)
    op.create_index(op.f('ix_protocol_fees_collected'), 'protocol_fees', ['collected'], unique=False)
    op.create_index(op.f('ix_protocol_fees_user_id'), 'protocol_fees', ['user_id'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_cdp_owner_wallet_address'), 'users', ['cdp_owner_wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_cdp_owner_wallet_address'), table_name='users')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_protocol_fees_user_id'), table_name='protocol_fees')
    op.drop_index(op.f('ix_protocol_fees_collected'), table_name='protocol_fees')
    op.drop_index(op.f('ix_positions_user_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_pool_address'), table_name='positions')
    op.drop_index(op.f('ix_strategy_decisions_user_id'), table_name='strategy_decisions')
    op.drop_index(op.f('ix_strategy_decisions_request_id'), table_name='strategy_decisions')
    op.drop_index(op.f('ix_strategy_decisions_pool_address'), table_name='strategy_decisions')
    op.drop_index('idx_strategy_decision_user', table_name='strategy_decisions')
    op.drop_index('idx_strategy_decision_type', table_name='strategy_decisions')
    op.drop_index('idx_strategy_decision_pool', table_name='strategy_decisions')
    op.drop_index('idx_strategy_decision_executed', table_name='strategy_decisions')
    op.drop_index('idx_strategy_decision_created', table_name='strategy_decisions')
    op.drop_index('idx_strategy_decision_action', table_name='strategy_decisions')
    op.drop_table('strategy_decisions')
    op.drop_index(op.f('ix_pool_metrics_pool_address'), table_name='pool_metrics')
    op.drop_index('idx_pool_metrics_volume', table_name='pool_metrics')
    op.drop_index('idx_pool_metrics_updated_at', table_name='pool_metrics')
    op.drop_index('idx_pool_metrics_tvl', table_name='pool_metrics')
    op.drop_index('idx_pool_metrics_is_stable', table_name='pool_metrics')
    op.drop_index('idx_pool_metrics_gauge', table_name='pool_metrics')
    op.drop_index('idx_pool_metrics_apr', table_name='pool_metrics')
    op.drop_table('pool_metrics')
    op.drop_index(op.f('ix_executor_stats_executor_id'), table_name='executor_stats')
    op.drop_index('idx_executor_stats_type', table_name='executor_stats')
    op.drop_index('idx_executor_stats_heartbeat', table_name='executor_stats')
    op.drop_index('idx_executor_stats_healthy', table_name='executor_stats')
    op.drop_index('idx_executor_stats_active', table_name='executor_stats')
    op.drop_table('executor_stats')
    op.drop_index('idx_daily_metrics_volume', table_name='daily_metrics')
    op.drop_index('idx_daily_metrics_type', table_name='daily_metrics')
    op.drop_index('idx_daily_metrics_tvl', table_name='daily_metrics')
    op.drop_index('idx_daily_metrics_date', table_name='daily_metrics')
    op.drop_table('daily_metrics')
    # ### end Alembic commands ###